### ISSUE TITLE
Peril master crashing on a PR

### ISSUE THREAD

**Issue by orta** [danger/peril#154]
```sh
2017-10-02T17:26:43.478633+00:00 app[web.1]: info: [router] - Passing pull_request to GH Dangerfile rule router
2017-10-02T17:26:43.479020+00:00 app[web.1]: info: [runner] - Event Settings: {
2017-10-02T17:26:43.479022+00:00 app[web.1]:  "commentableID": 778,
2017-10-02T17:26:43.479023+00:00 app[web.1]:  "eventID": "Unknown",
2017-10-02T17:26:43.479023+00:00 app[web.1]:  "hasRelatedCommentable": true,
2017-10-02T17:26:43.479024+00:00 app[web.1]:  "installationID": 23511,
2017-10-02T17:26:43.479025+00:00 app[web.1]:  "installationSettings": {
2017-10-02T17:26:43.479025+00:00 app[web.1]:   "env_vars": [
2017-10-02T17:26:43.479026+00:00 app[web.1]:    "SLACK_RFC_WEBHOOK_URL"
2017-10-02T17:26:43.479027+00:00 app[web.1]:   ],
2017-10-02T17:26:43.479027+00:00 app[web.1]:   "ignored_repos": [
2017-10-02T17:26:43.479028+00:00 app[web.1]:    "artsy/looker"
2017-10-02T17:26:43.479028+00:00 app[web.1]:   ],
2017-10-02T17:26:43.479029+00:00 app[web.1]:   "modules": [
2017-10-02T17:26:43.479030+00:00 app[web.1]:    "danger-plugin-spellcheck",
2017-10-02T17:26:43.479030+00:00 app[web.1]:    "danger-plugin-yarn",
2017-10-02T17:26:43.479032+00:00 app[web.1]:  "isRepoEvent": true,
2017-10-02T17:26:43.479035+00:00 app[web.1]:  "triggeredByUsername": "orta"
2017-10-02T17:26:43.479031+00:00 app[web.1]:    "@slack/client"
2017-10-02T17:26:43.479034+00:00 app[web.1]:  "repoName": "artsy/emission",
2017-10-02T17:26:43.539496+00:00 app[web.1]: Error:  TypeError: Cannot read property 'env_vars' of undefined
2017-10-02T17:26:43.479031+00:00 app[web.1]:   ]
2017-10-02T17:26:43.479032+00:00 app[web.1]:  },
2017-10-02T17:26:43.479034+00:00 app[web.1]:  "repoSpecificRules": {},
2017-10-02T17:26:43.479033+00:00 app[web.1]:  "isTriggeredByUser": true,
2017-10-02T17:26:43.479035+00:00 app[web.1]: }
2017-10-02T17:26:43.534044+00:00 app[web.1]: info: [runner] - Running Danger
2017-10-02T17:26:43.539499+00:00 app[web.1]:     at Object.exports.perilObjectForInstallation (/app/out/danger/danger_runner.js:42:18)
2017-10-02T17:26:43.539501+00:00 app[web.1]:     at fulfilled (/app/out/danger/danger_runner.js:4:58)
2017-10-02T17:26:43.539500+00:00 app[web.1]:     at Object.<anonymous> (/app/out/danger/danger_runner.js:36:31)
2017-10-02T17:26:43.539501+00:00 app[web.1]:     at Generator.next (<anonymous>)
2017-10-02T17:26:43.539502+00:00 app[web.1]:     at <anonymous>
2017-10-02T17:26:43.539503+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7)
2017-10-02T17:26:43.541790+00:00 app[web.1]: /app/out/peril.js:14
2017-10-02T17:26:43.541792+00:00 app[web.1]:         throw reason;
2017-10-02T17:26:43.541793+00:00 app[web.1]:         ^
2017-10-02T17:26:43.541794+00:00 app[web.1]:
2017-10-02T17:26:43.541794+00:00 app[web.1]: TypeError: Cannot read property 'env_vars' of undefined
2017-10-02T17:26:43.541795+00:00 app[web.1]:     at Object.exports.perilObjectForInstallation (/app/out/danger/danger_runner.js:42:18)
2017-10-02T17:26:43.541796+00:00 app[web.1]:     at Object.<anonymous> (/app/out/danger/danger_runner.js:36:31)
2017-10-02T17:26:43.541797+00:00 app[web.1]:     at Generator.next (<anonymous>)
2017-10-02T17:26:43.541798+00:00 app[web.1]:     at fulfilled (/app/out/danger/danger_runner.js:4:58)
2017-10-02T17:26:43.541798+00:00 app[web.1]:     at <anonymous>
2017-10-02T17:26:43.541799+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7)
2017-10-02T17:26:43.552345+00:00 app[web.1]: info: [CLUSTER] Worker 68 died with code: 1, and signal: null
2017-10-02T17:26:43.552428+00:00 app[web.1]: info: [CLUSTER] Starting a new worker
```

**Comment by orta** [comment]
Closing, likely fixed
