### ISSUE TITLE
Heroku deployment fails

### ISSUE THREAD

**Issue by danpalmer** [danger/peril#163]
I've been following the documentation to deploy an org install of Peril here: https://github.com/danger/peril/blob/master/docs/setup_for_org.md

I've created a repo with a `settings.json`:
```json
{
  "settings": {
  },
  "rules": {
    "pull_request": "review.js"
  },
  "repos" : {
  }
}
```

...and a `review.js`:

```js
import {message} from "danger"

message("Hello from the code review bot.")
```

This was basically just copied from orta/peril-bootstrap.

I've filled out all the required fields for the Heroku deployment, including the `DATABASE_JSON_FILE` setting of `our-org/our-code-review-repo@settings.json`.

When I click "Deploy", the deployment fails with the following log:

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  8.4
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 8.4...
       Downloading and installing node 8.4.0...
       Using default npm version: 5.3.0
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.3.2)...
       Installed yarn 1.3.2
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v1.3.2
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.1.1: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
       info fsevents@1.1.2: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning " > node-pg-migrate@2.7.0" has unmet peer dependency "pg@>=4.3.0 <8.0.0".
       warning "danger-plugin-spellcheck > markdown-spellcheck > sinon-as-promised@4.0.3" has unmet peer dependency "sinon@1".
       [4/4] Building fresh packages...
       $ yarn build
       yarn run v1.3.2
       $ yarn build:peril && yarn build:runner
       $ tsc
       $ webpack
       Hash: fe2b26200c36e206cb28
       Version: webpack 3.8.1
       Time: 3320ms
       Asset     Size  Chunks             Chunk Names
       peril-runner-dist.js  2.71 kB       0  [emitted]  main
       [0] ./source/peril-runner.ts 155 bytes {0} [built]
       Done in 9.15s.
       $ if [ $DATABASE_JSON_FILE ]; then yarn run setup; fi
       yarn run v1.3.2
       $ yarn run setup:plugins && yarn run setup:env
       $ ts-node source/scripts/setup-plugins.ts
       
       /tmp/build_6691d18f4d9cf6b25fb5b4b42e6d211e/danger-peril-b6e57bc/node_modules/ts-node/src/index.ts:312
       throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
       ^
       TSError: ⨯ Unable to compile TypeScript
       Cannot find type definition file for 'body-parser'. (2688)
       Cannot find type definition file for 'debug'. (2688)
       Cannot find type definition file for 'ejs'. (2688)
       Cannot find type definition file for 'express'. (2688)
       Cannot find type definition file for 'express-serve-static-core'. (2688)
       Cannot find type definition file for 'jest'. (2688)
       Cannot find type definition file for 'jsonwebtoken'. (2688)
       Cannot find type definition file for 'mime'. (2688)
       Cannot find type definition file for 'node'. (2688)
       Cannot find type definition file for 'node-fetch'. (2688)
       Cannot find type definition file for 'pg'. (2688)
       Cannot find type definition file for 'pg-promise'. (2688)
       Cannot find type definition file for 'pg-types'. (2688)
       Cannot find type definition file for 'serve-static'. (2688)
       Cannot find type definition file for 'winston'. (2688)
       source/scripts/setup-plugins.ts (1,32): Cannot find module 'child_process'. (2307)
       source/scripts/setup-plugins.ts (3,26): Cannot find module '../db/json'. (2307)
       source/scripts/setup-plugins.ts (4,36): Cannot find module '../globals'. (2307)
       source/scripts/setup-plugins.ts (6,13): Cannot find name 'console'. (2304)
       source/scripts/setup-plugins.ts (23,17): Cannot find name 'process'. (2304)
       source/scripts/setup-plugins.ts (31,7): Cannot find name 'process'. (2304)
       source/scripts/setup-plugins.ts (35,5): Cannot find name 'process'. (2304)
       at getOutput (/tmp/build_6691d18f4d9cf6b25fb5b4b42e6d211e/danger-peril-b6e57bc/node_modules/ts-node/src/index.ts:312:15)
       at /tmp/build_6691d18f4d9cf6b25fb5b4b42e6d211e/danger-peril-b6e57bc/node_modules/ts-node/src/index.ts:343:16
       at Object.compile (/tmp/build_6691d18f4d9cf6b25fb5b4b42e6d211e/danger-peril-b6e57bc/node_modules/ts-node/src/index.ts:485:17)
       at Module.m._compile (/tmp/build_6691d18f4d9cf6b25fb5b4b42e6d211e/danger-peril-b6e57bc/node_modules/ts-node/src/index.ts:395:43)
       at Module._extensions..js (module.js:584:10)
       at Object.require.extensions.(anonymous function) [as .ts] (/tmp/build_6691d18f4d9cf6b25fb5b4b42e6d211e/danger-peril-b6e57bc/node_modules/ts-node/src/index.ts:398:12)
       at Module.load (module.js:507:32)
       at tryModuleLoad (module.js:470:12)
       at Function.Module._load (module.js:462:3)
       at Function.Module.runMain (module.js:609:10)
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - A module may be missing from 'dependencies' in package.json
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
       
       - This module may be specified in 'devDependencies' instead of 'dependencies'
       https://devcenter.heroku.com/articles/nodejs-support#devdependencies
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

I'm afraid I haven't used TypeScript at all, and don't really know how it fits into the JS ecosystem in terms of packaged publishing types, etc, so I don't know if some of those errors are expected, and how to resolve this issue.

Happy to help debug this, but I could use some direction on what to try. Thanks in advance!

**Comment by orta** [comment]
Ah yeah, I think for now this can be fixed by removing the webpack/AWS side of Peril ( It's super early, I probably shouldn't have merged #162 yet ) - any chance you can try pushing 0a6b2a5cb38e9917b6c244896e46c96f5d41fa6e instead?

**Comment by danpalmer** [comment]
I don’t think that’s possible with the Heroku auto-deployment so I’ll need to figure out an alternative way. I might be able to try later. 

Thanks for the help!

**Comment by orta** [comment]
I've reverted master, _should_ work now

**Comment by danpalmer** [comment]
Perfect! Thanks for the help!
