### ISSUE TITLE
Peril immediately crashes on startup

### ISSUE THREAD

**Issue by mxstbr** [danger/peril#220]
- I followed the steps outlined in the "Run Peril for your org" doc
- Created GitHub app
- Created repo with settings: https://github.com/withspectrum/peril-settings
- Deployed to Heroku with all env vars except for "DANGER_BOT_ID" set (and set correctly, I double-checked)
- This error happens immediately upon startup, and keeps crashing the server over and over and over:

![screen shot 2018-03-20 at 17 23 19](https://user-images.githubusercontent.com/7525670/37676879-7cdd160a-2c79-11e8-812e-88b3af63c535.png)

<details>
  <summary>Click to see full logs</summary>

```sh
2018-03-20T18:58:22.348145+00:00 app[web.1]: info: [CLUSTER] Starting a new worker
2018-03-20T18:58:22.437226+00:00 app[web.1]: info: [CLUSTER] Worker 446 is online
2018-03-20T18:58:22.500521+00:00 app[web.1]: Skipping papertrail setup for winston.
2018-03-20T18:58:23.077093+00:00 app[web.1]: info: Using withspectrum/peril-settings@settings.json as a JSON db
2018-03-20T18:58:23.153510+00:00 app[web.1]: error: Error:  TypeError: Request with GET/HEAD method cannot have body
2018-03-20T18:58:23.153514+00:00 app[web.1]:     at new Request (/app/node_modules/node-fetch/lib/index.js:1166:10)
2018-03-20T18:58:23.153516+00:00 app[web.1]:     at /app/node_modules/node-fetch/lib/index.js:1344:19
2018-03-20T18:58:23.153518+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.153523+00:00 app[web.1]:     at fetch (/app/node_modules/node-fetch/lib/index.js:1342:9)
2018-03-20T18:58:23.153525+00:00 app[web.1]:     at Object.fetch [as default] (/app/out/api/fetch.js:34:12)
2018-03-20T18:58:23.153527+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:92:31
2018-03-20T18:58:23.153528+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-03-20T18:58:23.153530+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:7:71
2018-03-20T18:58:23.153532+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.153533+00:00 app[web.1]:     at __awaiter (/app/out/github/lib/github_helpers.js:3:12)
2018-03-20T18:58:23.153897+00:00 app[web.1]: /app/out/peril.js:18
2018-03-20T18:58:23.153903+00:00 app[web.1]:         throw reason;
2018-03-20T18:58:23.153905+00:00 app[web.1]:         ^
2018-03-20T18:58:23.153907+00:00 app[web.1]: 
2018-03-20T18:58:23.153908+00:00 app[web.1]: TypeError: Request with GET/HEAD method cannot have body
2018-03-20T18:58:23.153910+00:00 app[web.1]:     at new Request (/app/node_modules/node-fetch/lib/index.js:1166:10)
2018-03-20T18:58:23.153912+00:00 app[web.1]:     at /app/node_modules/node-fetch/lib/index.js:1344:19
2018-03-20T18:58:23.153913+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.153915+00:00 app[web.1]:     at fetch (/app/node_modules/node-fetch/lib/index.js:1342:9)
2018-03-20T18:58:23.153917+00:00 app[web.1]:     at Object.fetch [as default] (/app/out/api/fetch.js:34:12)
2018-03-20T18:58:23.153918+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:92:31
2018-03-20T18:58:23.153920+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-03-20T18:58:23.153922+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:7:71
2018-03-20T18:58:23.153923+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.153925+00:00 app[web.1]:     at __awaiter (/app/out/github/lib/github_helpers.js:3:12)
2018-03-20T18:58:23.159716+00:00 app[web.1]: info: [CLUSTER] Worker 446 died with code: 1, and signal: null
2018-03-20T18:58:23.159862+00:00 app[web.1]: info: [CLUSTER] Starting a new worker
2018-03-20T18:58:23.251927+00:00 app[web.1]: info: [CLUSTER] Worker 452 is online
2018-03-20T18:58:23.309386+00:00 app[web.1]: Skipping papertrail setup for winston.
2018-03-20T18:58:23.882927+00:00 app[web.1]: info: Using withspectrum/peril-settings@settings.json as a JSON db
2018-03-20T18:58:23.928104+00:00 app[web.1]: error: Error:  TypeError: Request with GET/HEAD method cannot have body
2018-03-20T18:58:23.928106+00:00 app[web.1]:     at new Request (/app/node_modules/node-fetch/lib/index.js:1166:10)
2018-03-20T18:58:23.928109+00:00 app[web.1]:     at /app/node_modules/node-fetch/lib/index.js:1344:19
2018-03-20T18:58:23.928111+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.928112+00:00 app[web.1]:     at fetch (/app/node_modules/node-fetch/lib/index.js:1342:9)
2018-03-20T18:58:23.928113+00:00 app[web.1]:     at Object.fetch [as default] (/app/out/api/fetch.js:34:12)
2018-03-20T18:58:23.928115+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:92:31
2018-03-20T18:58:23.928116+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-03-20T18:58:23.928117+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:7:71
2018-03-20T18:58:23.928118+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.928119+00:00 app[web.1]:     at __awaiter (/app/out/github/lib/github_helpers.js:3:12)
2018-03-20T18:58:23.928342+00:00 app[web.1]: /app/out/peril.js:18
2018-03-20T18:58:23.928345+00:00 app[web.1]:         throw reason;
2018-03-20T18:58:23.928347+00:00 app[web.1]:         ^
2018-03-20T18:58:23.928349+00:00 app[web.1]: 
2018-03-20T18:58:23.928350+00:00 app[web.1]: TypeError: Request with GET/HEAD method cannot have body
2018-03-20T18:58:23.928352+00:00 app[web.1]:     at new Request (/app/node_modules/node-fetch/lib/index.js:1166:10)
2018-03-20T18:58:23.928354+00:00 app[web.1]:     at /app/node_modules/node-fetch/lib/index.js:1344:19
2018-03-20T18:58:23.928355+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.928357+00:00 app[web.1]:     at fetch (/app/node_modules/node-fetch/lib/index.js:1342:9)
2018-03-20T18:58:23.928358+00:00 app[web.1]:     at Object.fetch [as default] (/app/out/api/fetch.js:34:12)
2018-03-20T18:58:23.928360+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:92:31
2018-03-20T18:58:23.928361+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-03-20T18:58:23.928363+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:7:71
2018-03-20T18:58:23.928365+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:23.928366+00:00 app[web.1]:     at __awaiter (/app/out/github/lib/github_helpers.js:3:12)
2018-03-20T18:58:23.933931+00:00 app[web.1]: info: [CLUSTER] Worker 452 died with code: 1, and signal: null
2018-03-20T18:58:23.933988+00:00 app[web.1]: info: [CLUSTER] Starting a new worker
2018-03-20T18:58:24.013764+00:00 app[web.1]: info: [CLUSTER] Worker 458 is online
2018-03-20T18:58:24.057782+00:00 app[web.1]: Skipping papertrail setup for winston.
2018-03-20T18:58:24.669760+00:00 app[web.1]: info: Using withspectrum/peril-settings@settings.json as a JSON db
2018-03-20T18:58:24.716106+00:00 app[web.1]: error: Error:  TypeError: Request with GET/HEAD method cannot have body
2018-03-20T18:58:24.716109+00:00 app[web.1]:     at new Request (/app/node_modules/node-fetch/lib/index.js:1166:10)
2018-03-20T18:58:24.716111+00:00 app[web.1]:     at /app/node_modules/node-fetch/lib/index.js:1344:19
2018-03-20T18:58:24.716114+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:24.716116+00:00 app[web.1]:     at fetch (/app/node_modules/node-fetch/lib/index.js:1342:9)
2018-03-20T18:58:24.716117+00:00 app[web.1]:     at Object.fetch [as default] (/app/out/api/fetch.js:34:12)
2018-03-20T18:58:24.716119+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:92:31
2018-03-20T18:58:24.716120+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-03-20T18:58:24.716122+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:7:71
2018-03-20T18:58:24.716124+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:24.716125+00:00 app[web.1]:     at __awaiter (/app/out/github/lib/github_helpers.js:3:12)
2018-03-20T18:58:24.716419+00:00 app[web.1]: /app/out/peril.js:18
2018-03-20T18:58:24.716421+00:00 app[web.1]:         throw reason;
2018-03-20T18:58:24.716423+00:00 app[web.1]:         ^
2018-03-20T18:58:24.716425+00:00 app[web.1]: 
2018-03-20T18:58:24.716427+00:00 app[web.1]: TypeError: Request with GET/HEAD method cannot have body
2018-03-20T18:58:24.716429+00:00 app[web.1]:     at new Request (/app/node_modules/node-fetch/lib/index.js:1166:10)
2018-03-20T18:58:24.716431+00:00 app[web.1]:     at /app/node_modules/node-fetch/lib/index.js:1344:19
2018-03-20T18:58:24.716432+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:24.716434+00:00 app[web.1]:     at fetch (/app/node_modules/node-fetch/lib/index.js:1342:9)
2018-03-20T18:58:24.716435+00:00 app[web.1]:     at Object.fetch [as default] (/app/out/api/fetch.js:34:12)
2018-03-20T18:58:24.716436+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:92:31
2018-03-20T18:58:24.716438+00:00 app[web.1]:     at Generator.next (<anonymous>)
2018-03-20T18:58:24.716439+00:00 app[web.1]:     at /app/out/github/lib/github_helpers.js:7:71
2018-03-20T18:58:24.716441+00:00 app[web.1]:     at new Promise (<anonymous>)
2018-03-20T18:58:24.716443+00:00 app[web.1]:     at __awaiter (/app/out/github/lib/github_helpers.js:3:12)
2018-03-20T18:58:24.721469+00:00 app[web.1]: info: [CLUSTER] Worker 458 died with code: 1, and signal: null
2018-03-20T18:58:24.721541+00:00 app[web.1]: info: [CLUSTER] Starting a new worker
2018-03-20T18:58:24.839136+00:00 app[web.1]: info: [CLUSTER] Worker 464 is online
2018-03-20T18:58:24.905217+00:00 app[web.1]: Skipping papertrail setup for winston.
2018-03-20T18:58:25.546204+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-03-20T18:58:25.546333+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-03-20T18:58:25.646062+00:00 heroku[web.1]: State changed from starting to crashed
2018-03-20T18:58:25.629853+00:00 heroku[web.1]: Process exited with status 137
```

</details>

<br />

<details>
  <summary>Click to see `settings.json`, or just go to the repo above</summary>

```JSON
{
  "settings": {
    "onlyForOrgMembers": false,
    "modules": ["danger-plugin-labels", "danger-plugin-flow", "danger-plugin-yarn", "danger-plugin-jest", "danger-plugin-no-test-shortcuts", "danger-plugin-no-console"]
  },
  "rules": {},
  "repos": {
    "withspectrum/spectrum": {
      "issue.opened": "withspectrum/spectrum@dangerfile.issues.js#auto-close-dumb-issues",
      "issue.edited": "withspectrum/spectrum@dangerfile.issues.js#auto-close-dumb-issues"
    }
  }
}
```

</details>

<br />

I'm not 100% sure how I can debug this as I've never really used Heroku. If you tell me how to get logs in there I'll happily get some more logs!

**Comment by orta** [comment]
Can confirm, I'm seeing this on Danger's Peril also

**Comment by orta** [comment]
Alright, you should update your heroku

You can do this by cloning peril locally, adding the heroku remote to git, then pushing to that remote

**Comment by mxstbr** [comment]
You're the best, thank you @orta!

**Comment by mxstbr** [comment]
I can confirm this is fixed :100:

**Comment by SD10** [comment]
Thank you for fixing this! I was banging my head against the wall 😆
