### ISSUE TITLE
Dangerfile on branch

### ISSUE THREAD

**Issue by mxstbr** [danger/peril#223]
I have my dangerfile on a branch, and specified that in the `settings.json` like so:

```JSON
{
  "settings": {
    "onlyForOrgMembers": false,
    "modules": ["danger-plugin-labels", "danger-plugin-flow", "danger-plugin-yarn", "danger-plugin-jest", "danger-plugin-no-test-shortcuts", "danger-plugin-no-console"]
  },
  "rules": {},
  "repos": {
    "withspectrum/spectrum": {
      "issues.opened": "withspectrum/spectrum@dangerfile.issues.js#auto-close-dumb-issues",
      "issues.edited": "withspectrum/spectrum@dangerfile.issues.js#auto-close-dumb-issues"
    }
  }
}
```

This is what the logs show when an issue is edited:

<details>
  <summary>Click to see logs</summary>

```
2018-03-21T13:22:26.806642+00:00 app[web.1]: info: [router] - Passing issues to GH Dangerfile rule router

2018-03-21T13:22:26.808913+00:00 app[web.1]: info: Found 1 runs for edited

2018-03-21T13:22:26.809526+00:00 app[web.1]: info: [runner] - Event Settings: {

2018-03-21T13:22:26.809529+00:00 app[web.1]:  "commentableID": 2633,

2018-03-21T13:22:26.809530+00:00 app[web.1]:  "eventID": "Unknown",

2018-03-21T13:22:26.809532+00:00 app[web.1]:  "hasRelatedCommentable": true,

2018-03-21T13:22:26.809534+00:00 app[web.1]:  "installationID": 114783,

2018-03-21T13:22:26.809536+00:00 app[web.1]:  "installationSettings": {

2018-03-21T13:22:26.809537+00:00 app[web.1]:   "env_vars": [],

2018-03-21T13:22:26.809539+00:00 app[web.1]:   "ignored_repos": [],

2018-03-21T13:22:26.809542+00:00 app[web.1]:   "modules": [

2018-03-21T13:22:26.809544+00:00 app[web.1]:    "danger-plugin-labels",

2018-03-21T13:22:26.809545+00:00 app[web.1]:    "danger-plugin-flow",

2018-03-21T13:22:26.809547+00:00 app[web.1]:    "danger-plugin-yarn",

2018-03-21T13:22:26.809549+00:00 app[web.1]:    "danger-plugin-jest",

2018-03-21T13:22:26.809550+00:00 app[web.1]:    "danger-plugin-no-test-shortcuts",

2018-03-21T13:22:26.809552+00:00 app[web.1]:    "danger-plugin-no-console"

2018-03-21T13:22:26.809554+00:00 app[web.1]:   ]

2018-03-21T13:22:26.809555+00:00 app[web.1]:  },

2018-03-21T13:22:26.809557+00:00 app[web.1]:  "isRepoEvent": true,

2018-03-21T13:22:26.809559+00:00 app[web.1]:  "isTriggeredByUser": true,

2018-03-21T13:22:26.809560+00:00 app[web.1]:  "repoName": "withspectrum/spectrum",

2018-03-21T13:22:26.809562+00:00 app[web.1]:  "repoSpecificRules": {

2018-03-21T13:22:26.809565+00:00 app[web.1]:   "issues.opened": "withspectrum/spectrum@dangerfile.issues.js#auto-close-dumb-issues",

2018-03-21T13:22:26.809567+00:00 app[web.1]:   "issues.edited": "withspectrum/spectrum@dangerfile.issues.js#auto-close-dumb-issues"

2018-03-21T13:22:26.809571+00:00 app[web.1]:  },

2018-03-21T13:22:26.809573+00:00 app[web.1]:  "triggeredByUsername": "mxstbr"

2018-03-21T13:22

:26.809574+00:00 app[web.1]: }

2018-03-21T13:22:26.941728+00:00 app[web.1]: error: res: https://api.github.com/repos/withspectrum/spectrum/contents/dangerfile.issues.js?

2018-03-21T13:22:26.941800+00:00 app[web.1]: error: Getting GitHub file failed: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

2018-03-21T13:22:26.942597+00:00 app[web.1]: info: [runner] - Running Danger

2018-03-21T13:22:26.947594+00:00 app[web.1]: error: Error:  ReferenceError: regeneratorRuntime is not defined

2018-03-21T13:22:26.947597+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/danger/distribution/runner/runners/vm2.js:71:84)

2018-03-21T13:22:26.947598+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/runners/vm2.js:40:23)

2018-03-21T13:22:26.947600+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/runners/vm2.js:21:53)

2018-03-21T13:22:26.947601+00:00 app[web.1]:     at /app/node_modules/danger/distribution/runner/runners/vm2.js:15:71

2018-03-21T13:22:26.947603+00:00 app[web.1]:     at new Promise (<anonymous>)

2018-03-21T13:22:26.947604+00:00 app[web.1]:     at __awaiter (/app/node_modules/danger/distribution/runner/runners/vm2.js:11:12)

2018-03-21T13:22:26.947605+00:00 app[web.1]:     at Object.createDangerfileRuntimeEnvironment (/app/node_modules/danger/distribution/runner/runners/vm2.js:57:12)

2018-03-21T13:22:26.947606+00:00 app[web.1]:     at /app/out/danger/danger_runner.js:52:46

2018-03-21T13:22:26.947608+00:00 app[web.1]:     at Generator.next (<anonymous>)

2018-03-21T13:22:26.947609+00:00 app[web.1]:     at /app/out/danger/danger_runner.js:7:71

2018-03-21T13:22:26.948025+00:00 app[web.1]: /app/out/peril.js:18

2018-03-21T13:22:26.948027+00:00 app[web.1]:         throw reason;

2018-03-21T13:22:26.948029+00:00 app[web.1]:         ^

2018-03-21T13:22:26.948030+00:00 app[web.1]: 

2018-03-21T13:22:26.948032+00:00 app[web.1]: ReferenceError: regeneratorRuntime is not defined

2018-03-21T13:22:

26.948033+00

:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/danger/distribution/runner/runners/vm2.js:71:84)

2018-03-21T13:22:26.948035+00:00 app[web.1]:     at step (/app/node_modules/danger/distribution/runner/runners/vm2.js:40:23)

2018-03-21T13:22:26.948036+00:00 app[web.1]:     at Object.next (/app/node_modules/danger/distribution/runner/runners/vm2.js:21:53)

2018-03-21T13:22:26.948038+00:00 app[web.1]:     at /app/node_modules/danger/distribution/runner/runners/vm2.js:15:71

2018-03-21T13:22:26.948039+00:00 app[web.1]:     at new Promise (<anonymous>)

2018-03-21T13:22:26.948040+00:00 app[web.1]:     at __awaiter (/app/node_modules/danger/distribution/runner/runners/vm2.js:11:12)

2018-03-21T13:22:26.948041+00:00 app[web.1]:     at Object.createDangerfileRuntimeEnvironment (/app/node_modules/danger/distribution/runner/runners/vm2.js:57:12)

2018-03-21T13:22:26.948043+00:00 app[web.1]:     at /app/out/danger/danger_runner.js:52:46

2018-03-21T13:22:26.948044+00:00 app[web.1]:     at Generator.next (<anonymous>)

2018-03-21T13:22:26.948045+00:00 app[web.1]:     at /app/out/danger/danger_runner.js:7:71

2018-03-21T13:22:26.955835+00:00 app[web.1]: info: [CLUSTER] Worker 30 died with code: 1, and signal: null
```

</details>

Any clues how to fix this apart from having to have the `settings.json` in the default branch? Or maybe the bug is the `regeneratorRuntime` being undefined? But that only happens afterwards...

**Comment by orta** [comment]
This should definitely be supported:

 - `https://api.github.com/repos/withspectrum/spectrum/contents/dangerfile.issues.js?` 

should be 

 -  `https://api.github.com/repos/withspectrum/spectrum/contents/dangerfile.issues.js?ref= auto-close-dumb-issues`

**Comment by mxstbr** [comment]
Any clues where that might be happening? Will happily submit a patch

**Comment by orta** [comment]
So the root cause is that the `getGitHubFileContentsFromLocation` here is not seeing a branch in the `dangerfileLocation` - https://github.com/danger/peril/blob/remove_body/source/runner/run.ts#L103-L104

**Comment by mxstbr** [comment]
Addin' some logs, will post result!

**Comment by mxstbr** [comment]
Put logs in both `runDangerEvent` and `runDangerPR` in that file (`logger.info(input.path, dangerfileLocation)`) but can't seem to trigger them 🤔

**Comment by mxstbr** [comment]
The issue  might be `github_runner.ts:197` instead, trying that.

**Comment by mxstbr** [comment]
It has `null` as the arg, so that'd make sense?

**Comment by mxstbr** [comment]
Gotta use that `dangerRepresentationforPath` util in `github_runner.ts` too I think, instead of defaulting the branch to `null`. Trying to make it work!

**Comment by mxstbr** [comment]
Oh wait, `run` already contains everything from `dangerRepresentationForPath`. 🤦‍♂️
