### ISSUE TITLE
Heroku auto deployment failing on github signing key

### ISSUE THREAD

**Issue by shortcircuit3** [danger/peril#241]
Noob question here so please excuse me..

I'm having trouble hosting Peril using the org tutorial.

- I followed all steps to create an app
- Double checked all keys
- Created github bot inside org
- Made settings repo public

The build fails with the following error and I tried recreate the private key a bunch of times and I followed the `pbcopy` instructions exactly. Kinda stumped 🙁 

```
$ yarn build; if [ $DATABASE_JSON_FILE ]; then yarn run setup; fi
       yarn run v1.6.0
       $ tsc
       Done in 5.90s.
       yarn run v1.6.0
       $ yarn run setup:plugins && yarn run setup:env
       $ node out/scripts/setup-plugins.js
       /tmp/build_0f760969e858dd6918e010440d598e1d/out/globals.js:56
       exports.PUBLIC_GITHUB_SIGNING_KEY = exports.publicKey.trim();
       ^
       
       TypeError: Cannot read property 'trim' of undefined
       at Object.<anonymous> (/tmp/build_0f760969e858dd6918e010440d598e1d/out/globals.js:56:55)
       at Module._compile (internal/modules/cjs/loader.js:654:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
       at Module.load (internal/modules/cjs/loader.js:566:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
       at Function.Module._load (internal/modules/cjs/loader.js:498:3)
       at Module.require (internal/modules/cjs/loader.js:598:17)
       at require (internal/modules/cjs/helpers.js:11:18)
       at Object.<anonymous> (/tmp/build_0f760969e858dd6918e010440d598e1d/out/api/github.js:3:19)
       at Module._compile (internal/modules/cjs/loader.js:654:30)
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       error Command failed with exit code 1.
```

After looking into the code, It seems to think I need `PUBLIC_GITHUB_SIGNING_KEY` 

https://github.com/danger/peril/blob/a7fd6eca2bc09df33a269a301d9106dbfab20be8/source/globals.ts#L39-L50

**Comment by orta** [comment]
Hrm, yeah the public key should be optional, so that trim needs to move off there

**Comment by milesalex** [comment]
🙌 Working now!! Thank you!!!!!!!

**Comment by orta** [comment]
Thank you for the easy to follow issue!
