### ISSUE TITLE
Adding an org to Peril caused 2 installations in the db

### ISSUE THREAD

**Issue by orta** [danger/peril#275]
![screen shot 2018-05-10 at 11 50 52 am](https://user-images.githubusercontent.com/49038/39879274-6a8a88ba-5448-11e8-943a-6e1e1247e3aa.png)

They both have the same iID.

**Comment by orta** [comment]
```
2018-05-10T15:47:41.861Z  info: ☢️  Starting up Peril
2018-05-10T15:47:41.883Z  info: ⅹ Papertrail
2018-05-10T15:47:41.905Z  info: ⅹ Clustering
2018-05-10T15:47:41.926Z  info: ✓ Mongo at ds253889.mlab.com:53889
2018-05-10T15:47:41.949Z  info: ✓ Task Scheduler
2018-05-10T15:47:41.971Z  info: ✓ Hyper Sandbox
2018-05-10T15:47:41.994Z  info: ✓ Docker Webhook
2018-05-10T15:47:42.016Z  info: ✓ Public API:
2018-05-10T15:47:42.038Z  info:   - Web Root: https://staging.peril.systems
2018-05-10T15:47:42.060Z  info:   - API Root: https://staging-api.peril.systems
2018-05-10T15:47:42.082Z  info:   - GraphQL : http://localhost:5000/api/graphql
2018-05-10T15:47:42.103Z  info:   - GraphiQL: http://localhost:5000/api/graphiql
2018-05-10T15:47:42.125Z  info: ✓ Server:
2018-05-10T15:47:42.147Z  info:   - Local: http://localhost:5000
2018-05-10T15:47:42.169Z  info:
2018-05-10T15:49:45.893Z  info:
2018-05-10T15:49:45.916Z  info: ## Creating new installation for artsy
2018-05-10T15:49:46.393Z  info:
2018-05-10T15:49:46.413Z  info: ## Creating new installation for artsy
2018-05-10T15:49:47.144Z  error: Error:  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
2018-05-10T15:49:46.921Z      at ServerResponse.setHeader (_http_outgoing.js:510:3)
2018-05-10T15:49:47.011Z      at ServerResponse.send (/home/nowuser/src/node_modules/express/lib/response.js:170:12)
2018-05-10T15:49:47.031Z      at Object.createInstallation (/home/nowuser/src/out/github/events/create_installation.js:18:25)
2018-05-10T15:49:47.052Z      at <anonymous>
2018-05-10T15:49:47.072Z      at process._tickCallback (internal/process/next_tick.js:118:7)
2018-05-10T15:49:47.092Z  /home/nowuser/src/out/peril.js:24
2018-05-10T15:49:47.113Z          throw reason;
2018-05-10T15:49:47.133Z          ^
2018-05-10T15:49:47.144Z      at validateHeader (_http_outgoing.js:503:11)
2018-05-10T15:49:47.145Z      at ServerResponse.header (/home/nowuser/src/node_modules/express/lib/response.js:767:10)
2018-05-10T15:49:47.154Z
2018-05-10T15:49:47.174Z  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
2018-05-10T15:49:47.199Z      at validateHeader (_http_outgoing.js:503:11)
2018-05-10T15:49:47.219Z      at ServerResponse.setHeader (_http_outgoing.js:510:3)
2018-05-10T15:49:47.240Z      at ServerResponse.header (/home/nowuser/src/node_modules/express/lib/response.js:767:10)
2018-05-10T15:49:47.260Z      at ServerResponse.send (/home/nowuser/src/node_modules/express/lib/response.js:170:12)
2018-05-10T15:49:47.280Z      at Object.createInstallation (/home/nowuser/src/out/github/events/create_installation.js:18:25)
2018-05-10T15:49:47.301Z      at <anonymous>
2018-05-10T15:49:47.321Z      at process._tickCallback (internal/process/next_tick.js:118:7)
```
