### ISSUE TITLE
Error in sending results back to Peril from runner

### ISSUE THREAD

**Issue by orta** [danger/peril#307]
```
2018-06-04T02:27:14.377Z      at <anonymous>
2018-06-04T02:27:14.432Z      at process._tickCallback (internal/process/next_tick.js:182:7)
2018-06-04T02:27:14.620Z      at dangerfileFinished (/home/nowuser/src/out/api/graphql/mutations/index.js:127:19)
2018-06-04T02:27:14.620Z  Error: JWT did not have access to run dangerfileFinished
```

Should only be happening on PR events atm because event runs don't trigger the `dangerfileFinished` mutation

**Comment by orta** [comment]
pretty sure this is fixed by https://github.com/danger/peril/compare/c2fc2a70a08b...8b90b4446c66
