### ISSUE TITLE
Peril staging is down because hyperfunc.io's cert expired

### ISSUE THREAD

**Issue by orta** [danger/peril#358]
```
2018-08-26T00:04:48.478Z  info: ## issues.opened on danger on danger/danger-js
2018-08-26T00:04:48.499Z  info:    1 run needed: org/org/checkTemplate.ts
2018-08-26T00:04:48.982Z  error: res: https://api.github.com/repos/danger/peril-settings/contents/org/org/checkTemplate.ts?ref=master
2018-08-26T00:04:49.356Z  error: Getting GitHub file failed: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}
2018-08-26T00:04:49.177Z  error: Error:  FetchError: request to https://us-west-1.hyperfunc.io/call/peril-staging/ failed, reason: certificate has expired
2018-08-26T00:04:49.252Z      at ClientRequest.<anonymous> (/home/nowuser/src/node_modules/node-fetch/lib/index.js:1393:11)
2018-08-26T00:04:49.366Z      at TLSSocket.socketErrorListener (_http_client.js:395:9)
2018-08-26T00:04:49.415Z      at TLSSocket.emit (events.js:180:13)
2018-08-26T00:04:49.437Z      at emitErrorNT (internal/streams/destroy.js:64:8)
2018-08-26T00:04:49.459Z      at process._tickCallback (internal/process/next_tick.js:178:19)
2018-08-26T00:04:49.745Z      at ClientRequest.emit (events.js:180:13)
2018-08-26T00:04:49.480Z
2018-08-26T00:04:49.502Z  /home/nowuser/src/node_modules/apollo-engine/lib/launcher.js:246
2018-08-26T00:04:49.523Z                  throw maybeError;
2018-08-26T00:04:49.546Z                  ^
2018-08-26T00:04:49.568Z  FetchError: request to https://us-west-1.hyperfunc.io/call/peril-staging/f81c11f9-273e-4921-8dfe-b0691f63ef80 failed, reason: certificate has expired
2018-08-26T00:04:49.590Z      at ClientRequest.<anonymous> (/home/nowuser/src/node_modules/node-fetch/lib/index.js:1393:11)
2018-08-26T00:04:49.611Z      at ClientRequest.emit (events.js:180:13)
2018-08-26T00:04:49.645Z      at TLSSocket.socketErrorListener (_http_client.js:395:9)
2018-08-26T00:04:49.667Z      at TLSSocket.emit (events.js:180:13)
2018-08-26T00:04:49.689Z      at emitErrorNT (internal/streams/destroy.js:64:8)
2018-08-26T00:04:49.712Z      at process._tickCallback (internal/process/next_tick.js:178:19)
2018-08-26T00:04:49.734Z  2018/08/26 00:04:49 http: proxy error: EOF
2018-08-26T00:04:51.559Z  (node:450) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2018-08-26T00:04:51.612Z  time="2018-08-26T00:04:51Z" level=info msg="Started HTTP server." address="[::]:5000" usingNamedPipe=false
2018-08-26T00:04:51.663Z  time="2018-08-26T00:04:51Z" level=info msg="Engine proxy started." build=2018.04-86-gf35bdc892 version=1.1.1
```

**Comment by orta** [comment]
Fixed and back on https
