### ISSUE TITLE
out/scripts/setup-env.js not found when deploying to Heroku

### ISSUE THREAD

**Issue by DivineDominion** [danger/peril#433]
Just been trying to set up Peril as an app for a GitHub Org. Ran into this error:

           Error: Cannot find module '/tmp/build_c937c0667aebea3b28d07e10947988c9/out/scripts/setup-env.js'

Which relates to https://github.com/danger/peril/blob/48e2124db3619e437420dbe3e154769435082b47/api/package.json#L17

But I'm not using node anytime in my life and don't know how this relates to dependencies or where else the missing script should come from.

## Complete Build Log

```
-----> Monorepo app detected
      Copied api to root of app successfully
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  10
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 10...
       Downloading and installing node 10.15.3...
       Using default npm version: 6.4.1
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.15.2)...
       Installed yarn 1.15.2
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.15.2
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@1.2.4: The platform "linux" is incompatible with this module.
       info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning "danger-plugin-spellcheck > markdown-spellcheck > sinon-as-promised@4.0.3" has unmet peer dependency "sinon@1".
       warning " > graphql-relay-tools@0.1.1" has incorrect peer dependency "graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0".
       warning " > graphql-schema-utils@0.6.5" has incorrect peer dependency "graphql@^0.8.2".
       warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".
       warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".
       [4/4] Building fresh packages...
       $ yarn build; if [ $DATABASE_JSON_FILE ]; then yarn run setup; fi
       yarn run v1.15.2
       $ tsc
       Done in 21.36s.
       yarn run v1.15.2
       $ yarn run setup:plugins && yarn run setup:env
       $ node out/scripts/setup-plugins.js
       Not adding any plugins
       $ node out/scripts/setup-env.js
       internal/modules/cjs/loader.js:584
           throw err;
           ^
       
       Error: Cannot find module '/tmp/build_c937c0667aebea3b28d07e10947988c9/out/scripts/setup-env.js'
           at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
           at Function.Module._load (internal/modules/cjs/loader.js:508:25)
           at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
           at startup (internal/bootstrap/node.js:283:19)
           at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - A module may be missing from 'dependencies' in package.json
         https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by rynocouse** [comment]
Looks like the source of scripts/setup-env.js -> `api/source/scripts/setup-env.ts` was removed in this commit: https://github.com/danger/peril/commit/26911cd5e55cac9009d3a5bc5e5afa21cbf1665f#diff-5b1851882068ba53d31daef457979857 I forked the repo and removed the `setup:env` task in package.json and Heroku deployed.
