### ISSUE TITLE
peril.runTask is not a function

### ISSUE THREAD

**Issue by roopakv** [danger/peril#459]
I keep getting this error when trying to run tasks. Not sure if anyone else has seen this. Will look into it again later this week.

```
TypeError: peril.runTask is not a function
at notifyIfMerged (/app/danger-0.5w3h1zhbghf.ts:13:21)
at Object.exports.default (/app/danger-0.5w3h1zhbghf.ts:22:15)
at Object.<anonymous> (/app/node_modules/danger/distribution/runner/runners/inline.js:147:60)
at step (/app/node_modules/danger/distribution/runner/runners/inline.js:32:23)
at Object.next (/app/node_modules/danger/distribution/runner/runners/inline.js:13:53)
at fulfilled (/app/node_modules/danger/distribution/runner/runners/inline.js:4:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by roopakv** [comment]
turns out runTask does not work without MongoDB.
