### ISSUE TITLE
Handle missing Dangerfile elegantly

### ISSUE THREAD

**Issue by orta** [danger/peril#73]
I think if the file is missing you get:

```
2017-05-05T20:16:45.287369+00:00 app[web.1]: info: [router] -  - passing to Dangerfile rule router
2017-05-05T20:16:45.288709+00:00 app[web.1]: info: [runner] - Event Settings: {
2017-05-05T20:16:45.288711+00:00 app[web.1]:  "commentableID": 1,
2017-05-05T20:16:45.288711+00:00 app[web.1]:  "isRepoEvent": true,
2017-05-05T20:16:45.288712+00:00 app[web.1]:  "isTriggeredByUser": true,
2017-05-05T20:16:45.288713+00:00 app[web.1]:  "repo": null,
2017-05-05T20:16:45.288714+00:00 app[web.1]:  "repoName": "artsy/artsy-danger",
2017-05-05T20:16:45.288714+00:00 app[web.1]:  "triggeredByUsername": "orta",
2017-05-05T20:16:45.288714+00:00 app[web.1]:  "hasRelatedCommentable": true
2017-05-05T20:16:45.288715+00:00 app[web.1]: }
2017-05-05T20:16:45.332220+00:00 app[web.1]: info: [runner] - Running: {
2017-05-05T20:16:45.332223+00:00 app[web.1]:  "event": "pull_request",
2017-05-05T20:16:45.332224+00:00 app[web.1]:  "action": "opened",
2017-05-05T20:16:45.332224+00:00 app[web.1]:  "dslType": 0,
2017-05-05T20:16:45.332225+00:00 app[web.1]:  "dangerfilePath": "blank.ts",
2017-05-05T20:16:45.332226+00:00 app[web.1]:  "repoSlug": "artsy/artsy-danger",
2017-05-05T20:16:45.332226+00:00 app[web.1]:  "feedback": 0
2017-05-05T20:16:45.332227+00:00 app[web.1]: }
2017-05-05T20:16:45.332313+00:00 app[web.1]: info: [runner] - Use fullDSL: true
2017-05-05T20:16:45.332395+00:00 app[web.1]: info: [runner] - supportGithubCommentAPIs: true
2017-05-05T20:16:45.391443+00:00 app[web.1]: info: [runner] - Running Danger: got API? null
2017-05-05T20:16:46.034269+00:00 app[web.1]: Error:  { Error: Cannot find module 'ts-jest' from 'blank.ts'
2017-05-05T20:16:46.034285+00:00 app[web.1]:     at Resolver.resolveModule (/app/node_modules/jest-resolve/build/index.js:169:17)
2017-05-05T20:16:46.034286+00:00 app[web.1]:     at Resolver._getVirtualMockPath (/app/node_modules/jest-resolve/build/index.js:289:23)
2017-05-05T20:16:46.034287+00:00 app[web.1]:     at Resolver._getAbsolutPath (/app/node_modules/jest-resolve/build/index.js:272:10)
2017-05-05T20:16:46.034287+00:00 app[web.1]:     at Resolver.getModuleID (/app/node_modules/jest-resolve/build/index.js:248:31)
2017-05-05T20:16:46.034288+00:00 app[web.1]:     at Runtime._shouldMock (/app/node_modules/jest-runtime/build/index.js:508:20)
2017-05-05T20:16:46.034289+00:00 app[web.1]:     at Runtime.requireModuleOrMock (/app/node_modules/jest-runtime/build/index.js:362:14)
2017-05-05T20:16:46.034290+00:00 app[web.1]:     at Object.<anonymous> (/tmp/0.ops22k27rl5lw71fefxn7b9/blank.ts:1:90)
2017-05-05T20:16:46.034290+00:00 app[web.1]:     at Runtime._execModule (/app/node_modules/jest-runtime/build/index.js:447:13)
2017-05-05T20:16:46.034291+00:00 app[web.1]:     at Runtime.requireModule (/app/node_modules/jest-runtime/build/index.js:295:14)
2017-05-05T20:16:46.034292+00:00 app[web.1]:     at /app/node_modules/danger/distribution/runner/DangerfileRunner.js:136:33 code: 'MODULE_NOT_FOUND' }
2017-05-05T20:16:46.034482+00:00 app[web.1]: /app/out/peril.js:11
2017-05-05T20:16:46.034483+00:00 app[web.1]:     throw reason;
2017-05-05T20:16:46.034484+00:00 app[web.1]:     ^
2017-05-05T20:16:46.034485+00:00 app[web.1]:
2017-05-05T20:16:46.034486+00:00 app[web.1]: Error: Cannot find module 'ts-jest' from 'blank.ts'
2017-05-05T20:16:46.034487+00:00 app[web.1]:     at Resolver.resolveModule (/app/node_modules/jest-resolve/build/index.js:169:17)
2017-05-05T20:16:46.034487+00:00 app[web.1]:     at Resolver._getVirtualMockPath (/app/node_modules/jest-resolve/build/index.js:289:23)
2017-05-05T20:16:46.034488+00:00 app[web.1]:     at Resolver._getAbsolutPath (/app/node_modules/jest-resolve/build/index.js:272:10)
2017-05-05T20:16:46.034488+00:00 app[web.1]:     at Resolver.getModuleID (/app/node_modules/jest-resolve/build/index.js:248:31)
2017-05-05T20:16:46.034489+00:00 app[web.1]:     at Runtime._shouldMock (/app/node_modules/jest-runtime/build/index.js:508:20)
2017-05-05T20:16:46.034490+00:00 app[web.1]:     at Runtime.requireModuleOrMock (/app/node_modules/jest-runtime/build/index.js:362:14)
2017-05-05T20:16:46.034490+00:00 app[web.1]:     at Object.<anonymous> (/tmp/0.ops22k27rl5lw71fefxn7b9/blank.ts:1:90)
2017-05-05T20:16:46.034491+00:00 app[web.1]:     at Runtime._execModule (/app/node_modules/jest-runtime/build/index.js:447:13)
2017-05-05T20:16:46.034492+00:00 app[web.1]:     at Runtime.requireModule (/app/node_modules/jest-runtime/build/index.js:295:14)
2017-05-05T20:16:46.034492+00:00 app[web.1]:     at /app/node_modules/danger/distribution/runner/DangerfileRunner.js:136:33
2017-05-05T20:16:46.049499+00:00 app[web.1]:
```

**Comment by orta** [comment]
That works to some extent: https://github.com/artsy/artsy-danger/pull/1

**Comment by orta** [comment]
This was because I deleted the branch that it's using for the Dangerfile

**Comment by orta** [comment]
This is now much better, I fixed some more work on this today.
